# Generated by Django 5.0.6 on 2026-06-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: server, code, network)", max_length=100)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre'],
            },
        ),
    ]
