# Generated by Django 5.0.6 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('societe', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('besoin', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('echeance', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('envoye', 'Envoyé'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='nouveau', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevisService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_services', to='devis.devis')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_services', to='services.service')),
            ],
            options={
                'verbose_name': 'Service demandé',
                'verbose_name_plural': 'Services demandés',
            },
        ),
        migrations.AddIndex(
            model_name='devis',
            index=models.Index(fields=['statut'], name='devis_devis_statut_a30d19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devisservice',
            unique_together={('devis', 'service')},
        ),
    ]
