# Generated by Django 5.0.6 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('domaine', models.CharField(max_length=100)),
                ('duree_heures', models.PositiveSmallIntegerField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('tous', 'Tous niveaux')], max_length=20)),
                ('programme', models.TextField()),
                ('tarif_min_gnf', models.DecimalField(decimal_places=0, max_digits=15)),
                ('tarif_max_gnf', models.DecimalField(decimal_places=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('format', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('intra', 'Intra-entreprise')], max_length=20)),
                ('places_max', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('complete', 'Complète'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='ouverte', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(choices=[('individuel', 'Individuel'), ('intra', 'Intra-entreprise'), ('pack', 'Pack Entreprise')], max_length=20)),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('especes', 'Espèces')], max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formations.session')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date_debut'], name='formations__date_de_4a329a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('user', 'session')},
        ),
    ]
