# Generated by Django 5.0.6 on 2026-06-01 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Format : LJX-AAAA-NNN', max_length=50, unique=True)),
                ('formule', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20)),
                ('montant_mensuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('termine', 'Terminé')], default='actif', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContratService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_services', to='contrats.contrat')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrat_services', to='services.service')),
            ],
            options={
                'verbose_name': 'Service du contrat',
                'verbose_name_plural': 'Services du contrat',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('impayee', 'Impayée'), ('en_retard', 'En retard')], default='impayee', max_length=20)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='contrats.contrat')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['statut'], name='contrats_co_statut_a74dc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contratservice',
            unique_together={('contrat', 'service')},
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut'], name='contrats_fa_statut_0edeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_echeance'], name='contrats_fa_date_ec_26f3be_idx'),
        ),
    ]
